version: "2.4"
services:
  chat_srvc_grpc:
    container_name: chat_srvc_grpc
    build:
      context: ./
      dockerfile: ./dockerfiles/chat_srvc_grpc/Dockerfile
    networks:
      grpc:
        ipv4_address: "172.16.238.11"

  auth_srvc_grpc:
    container_name: auth_srvc_grpc
    image: golang:latest
    restart: always
    volumes:
      - .:/go/src/auth_srvc_grpc
    command: make --directory=src/auth_srvc_grpc exec_auth_srvc
    networks:
      grpc:
        ipv4_address: "172.16.238.10"

  grpc_proxy:
    container_name: grpc_proxy
    build:
      context: ./
      dockerfile: ./dockerfiles/grpc_proxy/Dockerfile
    ports:
      - "4001:10010"
    networks:
      grpc:

  frontend_dev:
    container_name: frontend_dev
    image: node:12.18.4
    restart: always
    volumes:
      - ./web:/frontend
    ports:
      - "4000:3000"
    links:
      - grpc_proxy
    command: ./frontend/deploy.sh --dev

  frontend:
    container_name: frontend
    image: node:latest
    restart: always
    volumes:
      - ./web:/frontend
    ports:
      - "4000:3000"
    links:
      - grpc_proxy
    command: ./frontend/deploy.sh

networks:
  grpc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
