// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: pb/omegle.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChatResp_Status int32

const (
	ChatResp_OK          ChatResp_Status = 0
	ChatResp_UNAVAILABLE ChatResp_Status = 1
)

// Enum value maps for ChatResp_Status.
var (
	ChatResp_Status_name = map[int32]string{
		0: "OK",
		1: "UNAVAILABLE",
	}
	ChatResp_Status_value = map[string]int32{
		"OK":          0,
		"UNAVAILABLE": 1,
	}
)

func (x ChatResp_Status) Enum() *ChatResp_Status {
	p := new(ChatResp_Status)
	*p = x
	return p
}

func (x ChatResp_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatResp_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_omegle_proto_enumTypes[0].Descriptor()
}

func (ChatResp_Status) Type() protoreflect.EnumType {
	return &file_pb_omegle_proto_enumTypes[0]
}

func (x ChatResp_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatResp_Status.Descriptor instead.
func (ChatResp_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{1, 0}
}

type Payload_Kind int32

const (
	Payload_TEXT    Payload_Kind = 0
	Payload_IMAGE   Payload_Kind = 1
	Payload_VIDEO   Payload_Kind = 2
	Payload_CONTROL Payload_Kind = 3
)

// Enum value maps for Payload_Kind.
var (
	Payload_Kind_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "VIDEO",
		3: "CONTROL",
	}
	Payload_Kind_value = map[string]int32{
		"TEXT":    0,
		"IMAGE":   1,
		"VIDEO":   2,
		"CONTROL": 3,
	}
)

func (x Payload_Kind) Enum() *Payload_Kind {
	p := new(Payload_Kind)
	*p = x
	return p
}

func (x Payload_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payload_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_omegle_proto_enumTypes[1].Descriptor()
}

func (Payload_Kind) Type() protoreflect.EnumType {
	return &file_pb_omegle_proto_enumTypes[1]
}

func (x Payload_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payload_Kind.Descriptor instead.
func (Payload_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{6, 0}
}

type SendReceipt_Status int32

const (
	SendReceipt_OK    SendReceipt_Status = 0
	SendReceipt_ERROR SendReceipt_Status = 1
)

// Enum value maps for SendReceipt_Status.
var (
	SendReceipt_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	SendReceipt_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x SendReceipt_Status) Enum() *SendReceipt_Status {
	p := new(SendReceipt_Status)
	*p = x
	return p
}

func (x SendReceipt_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendReceipt_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_omegle_proto_enumTypes[2].Descriptor()
}

func (SendReceipt_Status) Type() protoreflect.EnumType {
	return &file_pb_omegle_proto_enumTypes[2]
}

func (x SendReceipt_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendReceipt_Status.Descriptor instead.
func (SendReceipt_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{7, 0}
}

type ChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requestor string `protobuf:"bytes,1,opt,name=requestor,proto3" json:"requestor,omitempty"`
	Requested string `protobuf:"bytes,2,opt,name=requested,proto3" json:"requested,omitempty"`
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{0}
}

func (x *ChatReq) GetRequestor() string {
	if x != nil {
		return x.Requestor
	}
	return ""
}

func (x *ChatReq) GetRequested() string {
	if x != nil {
		return x.Requested
	}
	return ""
}

type ChatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ChatResp_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ChatResp_Status" json:"status,omitempty"`
	Msg    string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResp) GetStatus() ChatResp_Status {
	if x != nil {
		return x.Status
	}
	return ChatResp_OK
}

func (x *ChatResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatsReq) Reset() {
	*x = StatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReq) ProtoMessage() {}

func (x *StatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReq.ProtoReflect.Descriptor instead.
func (*StatsReq) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{2}
}

type CommunityStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Online  int32 `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	Engaged int32 `protobuf:"varint,2,opt,name=engaged,proto3" json:"engaged,omitempty"`
}

func (x *CommunityStats) Reset() {
	*x = CommunityStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityStats) ProtoMessage() {}

func (x *CommunityStats) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityStats.ProtoReflect.Descriptor instead.
func (*CommunityStats) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{3}
}

func (x *CommunityStats) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *CommunityStats) GetEngaged() int32 {
	if x != nil {
		return x.Engaged
	}
	return 0
}

// JoinReq is a message conveying a request to join the Omegle chat service as a
// user.
type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // requested username for session
	Topics   []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{4}
}

func (x *JoinReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// User conveys an allocation on the Omegle service as a chat participant.
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Payload message conveys a payload from one user to another. Note that media
// payloads do not contain binary data but rather URLs to the media resources.
type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind Payload_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=pb.Payload_Kind" json:"kind,omitempty"`
	From string       `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To   string       `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Data string       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{6}
}

func (x *Payload) GetKind() Payload_Kind {
	if x != nil {
		return x.Kind
	}
	return Payload_TEXT
}

func (x *Payload) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Payload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Payload) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SendReceipt_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SendReceipt_Status" json:"status,omitempty"`
	Msg    string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendReceipt) Reset() {
	*x = SendReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_omegle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReceipt) ProtoMessage() {}

func (x *SendReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_pb_omegle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReceipt.ProtoReflect.Descriptor instead.
func (*SendReceipt) Descriptor() ([]byte, []int) {
	return file_pb_omegle_proto_rawDescGZIP(), []int{7}
}

func (x *SendReceipt) GetStatus() SendReceipt_Status {
	if x != nil {
		return x.Status
	}
	return SendReceipt_OK
}

func (x *SendReceipt) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_omegle_proto protoreflect.FileDescriptor

var file_pb_omegle_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x6f, 0x6d, 0x65, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x45, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x6c, 0x0a, 0x08,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x41,
	0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x22, 0x0a, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x42, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x65, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x64, 0x22, 0x3d, 0x0a, 0x07, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x22, 0x22, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9c, 0x01,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x10, 0x03, 0x22, 0x6c, 0x0a, 0x0b,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1b, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0xb4, 0x01, 0x0a, 0x06, 0x4f,
	0x6d, 0x65, 0x67, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x00, 0x30, 0x01, 0x12, 0x23, 0x0a, 0x04, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x26, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22,
	0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x61, 0x76, 0x61, 0x7a, 0x2d, 0x61, 0x6c, 0x61, 0x6e, 0x69, 0x2f, 0x6f, 0x6d, 0x65, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_omegle_proto_rawDescOnce sync.Once
	file_pb_omegle_proto_rawDescData = file_pb_omegle_proto_rawDesc
)

func file_pb_omegle_proto_rawDescGZIP() []byte {
	file_pb_omegle_proto_rawDescOnce.Do(func() {
		file_pb_omegle_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_omegle_proto_rawDescData)
	})
	return file_pb_omegle_proto_rawDescData
}

var file_pb_omegle_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_omegle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_omegle_proto_goTypes = []interface{}{
	(ChatResp_Status)(0),    // 0: pb.ChatResp.Status
	(Payload_Kind)(0),       // 1: pb.Payload.Kind
	(SendReceipt_Status)(0), // 2: pb.SendReceipt.Status
	(*ChatReq)(nil),         // 3: pb.ChatReq
	(*ChatResp)(nil),        // 4: pb.ChatResp
	(*StatsReq)(nil),        // 5: pb.StatsReq
	(*CommunityStats)(nil),  // 6: pb.CommunityStats
	(*JoinReq)(nil),         // 7: pb.JoinReq
	(*User)(nil),            // 8: pb.User
	(*Payload)(nil),         // 9: pb.Payload
	(*SendReceipt)(nil),     // 10: pb.SendReceipt
}
var file_pb_omegle_proto_depIdxs = []int32{
	0,  // 0: pb.ChatResp.status:type_name -> pb.ChatResp.Status
	1,  // 1: pb.Payload.kind:type_name -> pb.Payload.Kind
	2,  // 2: pb.SendReceipt.status:type_name -> pb.SendReceipt.Status
	7,  // 3: pb.Omegle.Join:input_type -> pb.JoinReq
	3,  // 4: pb.Omegle.Chat:input_type -> pb.ChatReq
	9,  // 5: pb.Omegle.Send:input_type -> pb.Payload
	5,  // 6: pb.Omegle.GetCommunityStats:input_type -> pb.StatsReq
	9,  // 7: pb.Omegle.Join:output_type -> pb.Payload
	4,  // 8: pb.Omegle.Chat:output_type -> pb.ChatResp
	10, // 9: pb.Omegle.Send:output_type -> pb.SendReceipt
	6,  // 10: pb.Omegle.GetCommunityStats:output_type -> pb.CommunityStats
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_omegle_proto_init() }
func file_pb_omegle_proto_init() {
	if File_pb_omegle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_omegle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_omegle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_omegle_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_omegle_proto_goTypes,
		DependencyIndexes: file_pb_omegle_proto_depIdxs,
		EnumInfos:         file_pb_omegle_proto_enumTypes,
		MessageInfos:      file_pb_omegle_proto_msgTypes,
	}.Build()
	File_pb_omegle_proto = out.File
	file_pb_omegle_proto_rawDesc = nil
	file_pb_omegle_proto_goTypes = nil
	file_pb_omegle_proto_depIdxs = nil
}
