// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pb/chat/chat.proto

#include "pb/chat/chat.pb.h"
#include "pb/chat/chat.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace chat {

static const char* Chat_method_names[] = {
  "/chat.Chat/Join",
  "/chat.Chat/Send",
  "/chat.Chat/Poll",
};

std::unique_ptr< Chat::Stub> Chat::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Chat::Stub> stub(new Chat::Stub(channel));
  return stub;
}

Chat::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Join_(Chat_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Send_(Chat_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Poll_(Chat_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Chat::Stub::Join(::grpc::ClientContext* context, const ::chat::JoinReq& request, ::chat::Receipt* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Join_, context, request, response);
}

void Chat::Stub::experimental_async::Join(::grpc::ClientContext* context, const ::chat::JoinReq* request, ::chat::Receipt* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Join_, context, request, response, std::move(f));
}

void Chat::Stub::experimental_async::Join(::grpc::ClientContext* context, const ::chat::JoinReq* request, ::chat::Receipt* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Join_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::Receipt>* Chat::Stub::PrepareAsyncJoinRaw(::grpc::ClientContext* context, const ::chat::JoinReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::chat::Receipt>::Create(channel_.get(), cq, rpcmethod_Join_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::chat::Receipt>* Chat::Stub::AsyncJoinRaw(::grpc::ClientContext* context, const ::chat::JoinReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncJoinRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Chat::Stub::Send(::grpc::ClientContext* context, const ::chat::Payload& request, ::chat::Receipt* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Send_, context, request, response);
}

void Chat::Stub::experimental_async::Send(::grpc::ClientContext* context, const ::chat::Payload* request, ::chat::Receipt* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void Chat::Stub::experimental_async::Send(::grpc::ClientContext* context, const ::chat::Payload* request, ::chat::Receipt* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::Receipt>* Chat::Stub::PrepareAsyncSendRaw(::grpc::ClientContext* context, const ::chat::Payload& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::chat::Receipt>::Create(channel_.get(), cq, rpcmethod_Send_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::chat::Receipt>* Chat::Stub::AsyncSendRaw(::grpc::ClientContext* context, const ::chat::Payload& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Chat::Stub::Poll(::grpc::ClientContext* context, const ::chat::PollReq& request, ::chat::PollUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Poll_, context, request, response);
}

void Chat::Stub::experimental_async::Poll(::grpc::ClientContext* context, const ::chat::PollReq* request, ::chat::PollUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Poll_, context, request, response, std::move(f));
}

void Chat::Stub::experimental_async::Poll(::grpc::ClientContext* context, const ::chat::PollReq* request, ::chat::PollUpdate* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Poll_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::PollUpdate>* Chat::Stub::PrepareAsyncPollRaw(::grpc::ClientContext* context, const ::chat::PollReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::chat::PollUpdate>::Create(channel_.get(), cq, rpcmethod_Poll_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::chat::PollUpdate>* Chat::Stub::AsyncPollRaw(::grpc::ClientContext* context, const ::chat::PollReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPollRaw(context, request, cq);
  result->StartCall();
  return result;
}

Chat::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Chat_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Chat::Service, ::chat::JoinReq, ::chat::Receipt>(
          [](Chat::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::JoinReq* req,
             ::chat::Receipt* resp) {
               return service->Join(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Chat_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Chat::Service, ::chat::Payload, ::chat::Receipt>(
          [](Chat::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::Payload* req,
             ::chat::Receipt* resp) {
               return service->Send(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Chat_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Chat::Service, ::chat::PollReq, ::chat::PollUpdate>(
          [](Chat::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::PollReq* req,
             ::chat::PollUpdate* resp) {
               return service->Poll(ctx, req, resp);
             }, this)));
}

Chat::Service::~Service() {
}

::grpc::Status Chat::Service::Join(::grpc::ServerContext* context, const ::chat::JoinReq* request, ::chat::Receipt* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Chat::Service::Send(::grpc::ServerContext* context, const ::chat::Payload* request, ::chat::Receipt* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Chat::Service::Poll(::grpc::ServerContext* context, const ::chat::PollReq* request, ::chat::PollUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

