// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	GetCert(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Cert, error)
	VerifCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*CertStatus, error)
	RenewCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*Cert, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetCert(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Cert, error) {
	out := new(Cert)
	err := c.cc.Invoke(ctx, "/auth.Auth/GetCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) VerifCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*CertStatus, error) {
	out := new(CertStatus)
	err := c.cc.Invoke(ctx, "/auth.Auth/VerifCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RenewCert(ctx context.Context, in *Cert, opts ...grpc.CallOption) (*Cert, error) {
	out := new(Cert)
	err := c.cc.Invoke(ctx, "/auth.Auth/RenewCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	GetCert(context.Context, *Request) (*Cert, error)
	VerifCert(context.Context, *Cert) (*CertStatus, error)
	RenewCert(context.Context, *Cert) (*Cert, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) GetCert(context.Context, *Request) (*Cert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCert not implemented")
}
func (UnimplementedAuthServer) VerifCert(context.Context, *Cert) (*CertStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifCert not implemented")
}
func (UnimplementedAuthServer) RenewCert(context.Context, *Cert) (*Cert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCert not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_GetCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/GetCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetCert(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_VerifCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).VerifCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/VerifCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).VerifCert(ctx, req.(*Cert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RenewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RenewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/RenewCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RenewCert(ctx, req.(*Cert))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCert",
			Handler:    _Auth_GetCert_Handler,
		},
		{
			MethodName: "VerifCert",
			Handler:    _Auth_VerifCert_Handler,
		},
		{
			MethodName: "RenewCert",
			Handler:    _Auth_RenewCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth/auth.proto",
}
